name: Run VM Supervisor
on: [push]
jobs:
  Run-VM-Supervisor-Fake-Data:
    runs-on: self-hosted
    timeout-minutes: 10
    env:
      ALEPH_VM_FAKE_DATA: true
      ALEPH_VM_LINUX_PATH: /opt/vmlinux.bin
      ALEPH_VM_INIT_TIMEOUT: 20

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Ensure dependencies are present
        run: |
          sudo apt-get install --yes python3-pip docker.io debootstrap squashfs-tools
#          usermod -aG docker github-runner
#          usermod -aG sudo github-runner

      - name: Upgrade aleph-message
        run: pip3 install --upgrade aleph-message

      - name: Build the example squashfs
        run: |
          cd examples/volumes
          sudo bash build_squashfs.sh

      - name: Update the rootfs
        run: |
          cd runtimes/aleph-debian-11-python/
          sudo bash ./create_disk_image.sh
#          cp -pr /var/tmp/rootfs-debian ./rootfs
#          bash update_inits.sh

      - name: Build VM Connector
        run: |
          docker build -t aleph-connector -f docker/vm_connector.dockerfile .

      - name: Run the VM Connector
        run: |
          docker stop aleph-connector || true
          docker run -d --rm -p 8000:8000/tcp \
            -v $(pwd)/kernels:/opt/kernels:ro \
            -v $(pwd)/vm_connector:/opt/vm_connector:ro \
            --name aleph-connector \
            aleph-connector $@

      - name: Run the main entrypoint
        run: python3 -m vm_supervisor -p -vv --profile --print-settings --system-logs --benchmark=1

      - name: Stop the VM Connector
        run: |
          docker stop aleph-connector
